carforyou/carforyou-components-pkg

src/node.ts
https://autoricardo.atlassian.net/browse/CAR-4013
BREAKING CHANGE: components-pkg no longer exposes `getWhitelistPatterns`. if your application contains any dynamic width classes, you will need to handle them in your app
the w-*/* whitelist was added because some applications use dynamic widths. in my opinion, purging CSS is an application concern. if we continue whitelisting classes globally, even they're not required in the applications, we unnecessarily bloat CSS bundles. I verified that components-pkg only contains purgeable css
=> fix: remove getWhitelistPatterns

src/__tests__/__snapshots__/node.test.ts.snap, src/components/pill.tsx, src/index.ts, src/tailwind/defaultConfig.ts, stories/pill.stories.js
I will be using this in the header. the border-8 was not in the config and I want the header to use only tailwind values from components lib if possible
=> feat: add pill component

src/components/modal/index.tsx, src/hooks/__tests__/useModal.test.tsx, src/hooks/useModal.tsx, stories/input/generator.tsx, stories/modal/generator.tsx, stories/modal/index.stories.tsx
- fix: calls the onClose event when the user clicks on the overlay
- tests: unit tests for all onClose cases
- story book: adds example for the onClose event
=> fix: Modal onClose behaviour

src/__tests__/__snapshots__/node.test.ts.snap, src/components/tooltip/popUp.tsx, src/tailwind/defaultConfig.ts, stories/tooltip/generator.tsx
When we added the `Tooltip` component we assumed that the width will always be fixed. That's not the case - different designs show different tooltip widths.
This removes the hardcoded width class and moves the width setting to the content.
=> fix: do not hardcode tooltip width

assets/index.css, assets/tooltip.css, src/components/tooltip/index.tsx
It turns out that just using background colours of the tooltip can break border-radius in a rare case when the tooltip is displayed over images/elements with overflows.
**before**
**after**
Unfortunately, there's no way around custom CSS here, but I believe we can live with one simple class.
=> fix: ensure tooltip always has rouded corners

src/__tests__/__snapshots__/node.test.ts.snap, src/tailwind/defaultConfig.ts
We define the same `container` max-width in all the projects. We want to use the same value in the footer too.
=> feat: add container max-width

src/components/intercom/index.tsx
The current colour of intercom conflicts with the colour used for dealer promotion. This results in really shitty view on mobile where the button blends in with the promotion. After checking with Enrique we decided to switch to a darker shade of grey. 
**before**
**after**
=> feat: change intercom button colour

src/__tests__/__snapshots__/node.test.ts.snap, src/tailwind/defaultConfig.ts
we are missing some spacing values that we should have had. 
Further steps for the future:
- margins and paddings should take the value from the spacing section. Will create a ticket to migrate all the spacing values we are using to margins and paddings
=> feat: add new spacing values

assets/global.css
Fixes CAR-5561
The `preventScrolling` classes are dynamic and therefore stripped by purgeCSS.
=> fix: whitelist scrolling classes

src/components/modal/index.tsx, src/hooks/__tests__/__snapshots__/useModal.test.tsx.snap
Stumbled upon an issue with the fullscreen modal, where it overrides `fixed` on medium viewport:
*Before*
*After*
=> fix: fullscreen modal

assets/input/basic.css, src/__tests__/__snapshots__/node.test.ts.snap, src/components/dropdown/index.tsx, src/components/dropdown/menu.tsx, src/components/dropdown/withAutosuggest.tsx, src/components/input/index.tsx, src/components/select.tsx, src/stories/select/withAutosuggest/appearance.stories.js, src/tailwind/defaultConfig.ts
Reference: [CFYEO-39](https://autoricardo.atlassian.net/browse/CFYEO-39)
Some components provided the ability to pass classes as a prop. This gives the consumer of that component a lot of possibilities to mess around with the styling. Therefore, I removed them where possible.
Unfortunately, I was not able to remove the menuClassName prop as it will require a lot of restructuring or inventing new boolean props to achieve the same styling. However, I think this change provides a bit of value nevertheless as it improves consistency and does not allow className in other places now.
----
Here are the related PR's:
- dealerhub: https://github.com/carforyou/carforyou-dealerhub-web/pull/894
- listings: https://github.com/carforyou/carforyou-listings-web/pull/2801
- header-footer: not affected by …
=> CFYEO-39: Remove classname props

src/components/input/index.tsx, src/components/input/inputField.tsx
Makes the onChange event compatible with the default onChange event yielded by an input filed.
Use Case: We want to ad an input mask that formats the input for the user, the input mask library is submitting a `ChangeEvent<HTMLInputElement>` event, with the current typing the component can not be used as a wrapper ref: https://github.com/carforyou/carforyou-listings-web/pull/2861/files
=> fix: make the onChange event compatible with default input on change event

src/components/segmentedControl/__tests__/__snapshots__/index.test.tsx.snap, src/components/segmentedControl/button.tsx, src/components/segmentedControl/index.tsx, src/stories/segmentedControl.stories.tsx
https://autoricardo.atlassian.net/browse/CAR-6411
Currently all the segments are the same width, regardless of text content, which can lead to one segment being multiple lines. 
There are cases when we want to have dynamic width.
Before:
After:
=> feat: make segmented control grow

src/__tests__/__snapshots__/node.test.ts.snap, src/components/datePicker/index.tsx, src/components/menu/element.tsx, src/components/menu/item.tsx, src/components/menu/sectionTitle.tsx, src/components/select.tsx, src/index.ts, src/stories/menu/item.stories.tsx, src/stories/menu/sectionTitle.stories.tsx, src/tailwind/defaultConfig.ts
Extracts `MenuItem` and `MenuSectionTitle` components introduced in carforyou/carforyou-header-footer-pkg#112 so that we can use the same basis to create sidebar menu in dealer-hub.
=> feat: menu components

src/components/dropdown/menu.tsx
If the key is not defined on the options, it will use the value as the key. Because the value is often an object such as `{sortOrder: "ASC", sortType: "PRICE"}`, `value.toString()` will result in `[object Object]`.
As a result, the DOM is invalid because of duplicated keys
=> fix: menu item key

src/components/filters/input.tsx
References https://autoricardo.atlassian.net/browse/CAR-7009
While working on the inputFilter extraction, I found that when we apply the value on the type input in the Make & model section, the last character is deleted. This issue affects already DH.
Listings PR -> https://github.com/carforyou/carforyou-listings-web/pull/3073
DH PR -> https://github.com/carforyou/carforyou-dealerhub-web/pull/1191
=> fix: fixed applyFilter function

src/components/collapsible.tsx
Reference: [CAR-7124](https://autoricardo.atlassian.net/browse/CAR-7124)
In some pages in DH and listings, there is an error in the console that the DOM is invalid. The reason for it is that the collapsible itself is an `<a/>` tag. This does not allow to have other a tags within the collapsible component. As we have this requirement, I changed it here to a div.
=> fix: change <a/> to <div/> to allow links within the collapsible

src/components/collapsible.tsx
I missed one of the IT tests in listings that queried the `<a/>` tag. Because of the div, the selector is no longer possible because it found too many. 
I have a draft branch here with the fixed tests -> https://github.com/carforyou/carforyou-listings-web/pull/3090
=> fix: add test id for collapsible

src/components/menu/item.tsx
In case the menu item doesn't have a link wrapper we pass `href` prop to `React.Fragment`.
This results in warnings from react:
`href` prop is only passed when we don't use `Fragment` as default wrapper
=> fix: do not pass href prop to fragment

src/components/datePicker/index.module.css, src/components/modal/index.tsx, src/hooks/__tests__/__snapshots__/useModal.test.tsx.snap
References [CAR-7194](https://autoricardo.atlassian.net/browse/CAR-7194)
On iPhone 7 and iPhone X, the Calendar for test drive request are more towards the right of the screen.
Go to https://car7194.carforyou-listings-web.branch.carforyou.ch/
Check that the calendar is not wider than the input
=> fix: change padding

src/components/__tests__/__snapshots__/button.test.tsx.snap, src/components/__tests__/button.test.tsx, src/components/button.tsx, src/stories/button.stories.tsx
References https://autoricardo.atlassian.net/browse/CAR-7219
Other than adding a new disabled style for a button with a teal border this PR fixes how we set button style.
Before this was controlled by boolean props `teal` and `tealBorder`, which could lead to setting an "impossible" style (by setting both to true). This has now been replaced by `style` prop which accepts `salmon` (default), `teal` and `teal-border`.
Because of this, it will be a BREAKING CHANGE.
=> fix: align button style

src/components/__tests__/tabs.test.tsx, src/components/tabs.tsx, src/stories/tabs.stories.tsx
Implements CAR-7324
This PR adds a new `Tabs` component:
**Single tab**
**Multiple tabs**
**Tabs with icons**
=> feat: introduce tabs component

src/components/tabs.tsx
- due to the border being only rendered when the tab is not active text was jumping by 1px when switching between active/inactive. Since tailwind does not support variable border colours we fix it by adding margin when the tab is active
- the border separating tabs had corner pixel missing since it was only rendered on one side. Negative margin and rendering it on both sides fixes it.
=> fix: tabs jumping issues

src/components/tooltip/index.tsx
References CAR-7544 (https://autoricardo.atlassian.net/browse/CAR-7544)
1. in some cases we forget and then do retroactive fixes. I'd like to find a solution that works out of the box without having to apply weird event handlers in every single tooltip
2. I'd like to understand better where the need for this is coming from. preferrably, we would always let the events bubble and not prevent them. there might be a fix in the tooltip library for this by now
Explicitly stop event propagation every place `Tooltip` is used.
Out of the box solution. event propagation is stopped in the `Tooltip` component 
* open a consumer app where the components pkg is used  (i.e Dealerhub)
* open listings page on Dealerhub
* make sure you're on Mobile
* open verified badge
* click the link
* it should simply …
=> fix(tooltip): stop event propagation

assets/pagination.css
> Jira https://autoricardo.atlassian.net/browse/CAR-7480
The range page label is not centered either the number in the circle.
------------------------------------
The range page label is centered either the number in the circle.
----------------------------
Please check it on mobile and desktop
You can see the results from listings here:
https://car-7480.carforyou-listings-web.branch.carforyou.ch/en/auto/mercedes-benz
https://car-7480.carforyou-listings-web.branch.carforyou.ch/en/auto/search
=> fix: center labels in pagination

src/components/badges/base.tsx, src/components/badges/buyerProtection.tsx, src/components/badges/verified.tsx
- fix: Only make the badge having a pointer cursor if there is a tooltip [ref](https://github.com/carforyou/carforyou-listings-web/pull/3246#issuecomment-858561423)
- fix: the colors for the verified and buyer protection badge for use cases like checkboxes in the filters [ref](https://github.com/carforyou/carforyou-listings-web/pull/3246#pullrequestreview-680884580)
- fix: make the bade background white in all uses cases [ref](https://github.com/carforyou/carforyou-listings-web/pull/3246#pullrequestreview-680677726)
=> fix: badges behaviour for various usecases

src/components/modal/index.tsx
References: https://autoricardo.atlassian.net/browse/CAR-7476
Fixes horizontal scroll on mobile in gallery, and some other modals in DH. 
`fullscreen` modal is used in these places:
**DH:**
- listingsOverviewContent.tsx
- index.tsx (this is my garage)
- printCenterContent.tsx
**Listings**:
- fullScreenSlider.tsx
I've checked all of them. Images below. 
This PR only changes the mobile view for the fullscreen modal.
Listings gallery:
My garage:
listingsOverviewContent and printCenterContent (these filters are pretty much the same):
Listings gallery:
My garage:
listingsOverviewContent and printCenterContent (these filters are pretty much the same):
=> fix: horizontal scroll on mobile

src/components/datePicker/index.tsx
Ref https://autoricardo.atlassian.net/browse/CAR-7632
If the selected date is cleared with the X in the input the callback was not executed, therefore the consuming component was not updated propperly
=> fix: update form value if input filed is cleared

src/hooks/useModal.tsx
open and close modal triggered a rerender of the whole parent component everytime they were called. 
Related PR: https://github.com/carforyou/carforyou-listings-web/pull/3341
=> CAR-7019: use callback for open and close modal to prevent rerenders

src/components/__tests__/__snapshots__/button.test.tsx.snap, src/components/__tests__/button.test.tsx, src/components/button.tsx, src/stories/button.stories.tsx
Reference: [CAR-8045](https://autoricardo.atlassian.net/browse/CAR-8045)
For the new make page, we need a white button:
I refactored the styles a bit and went for more duplication. It was no longer readable when adding another style
=> CAR-8045: new style "white" for button

src/components/modal/index.tsx
Accidentally I have moved the paddings for all the sizes but the fullscreen shouldn't have those paddings. Otherwise, it will be padding in the gallery modal in listings on the PDP and as a result a horizontal scrollbar.
=> fix: padding in gallery modal

src/components/badges/__tests__/gdbd.test.tsx, src/components/badges/gdbd.tsx
Due to changes in the calculation of `gdbScore`, there is no default anymore. That means `null` can be sent when the calculation is not yet finished on the BE side. We've been asked to handle `nulls` the same way as `not-defined` in the frontend since it's not feasible to set the default value on elasticsearch.
```
<GdbBadge score={null} />
```
Would render a black, unstyled label without text
```
<GdbBadge score={null} />
```
looks the same as
```
<GdbBadge score={"not-defined"} />
```
=> fix: handle null gbdScore gracefully

src/components/intercom/index.tsx
We never passed the `email` to Intercom, only the `userId`. Even if we ever passed the email, this is enough to detect a logged-in user.
Log into DH and log out again, Intercom retains the logged in state:
Log into DH and log out again, Intercom properly forgets the user and asks for contact details:
=> fix: logout behavior based on what we actually pass in the app

src/components/__tests__/rangeSelect.test.tsx, src/components/filters/input.tsx, src/components/rangeSelect.tsx
References CAR-8280
When we extracted range selects from listings we did not consider tracking in any way (probably because those filters weren't tracked). With new requirements and more and more filters being implemented it makes sense to support that.
I deliberately chose a separate prop to distinguish between applying the filter (change handler) and tracking (or doing something else with the selected value). This is consistent with the behaviour we have in the checkbox filter.
Same principle is followed with `onApply` prop for input filter that was also left out before
=> feat: add onSelect to range filter & onApply to input filter

assets/input/floatingLabel.css, src/components/input/index.tsx
Ref: https://autoricardo.atlassian.net/browse/CAR-8253
For the migrated buyer protection form we wanna use the HTML validation in the first version.
The floating label input makes every input required which prevents us from doing so.
Instead of using the `:valid` pseudo selector use the `:placeholder-shown` to make the label floating
Testing:
Check out the branch and ensure the floating labels are working the same as before
=> feat: do not rely on input being required to display the floating label

src/components/fieldHelpers/withClearButton.tsx, src/components/intercom/index.tsx
The size gets stripped with the new asset setup. Checked the other components they looked fine, most of them already define custom width height when consuming the icons.
Before
After
=> fix(intercom): size the chat icon

src/components/previewCard/index.tsx
References: https://autoricardo.atlassian.net/browse/CAR-8519
=> fix: add sizes to arrow icon on preview card

src/components/fieldHelpers/withLabel.tsx
https://autoricardo.atlassian.net/browse/CAR-8536
Icon was way too big. size got lost with #406
=> fix: info icon size for label popup

src/components/previewCard/index.tsx
Modern browsers support built-in lazy loading for images. It does not break anything in older browsers, it will be just ignored. This adds the ability for this to PreviewCard which is used for garage promotion on the HP
=> feat: allow to load image lazy for preview card

src/components/filters/__tests__/checkbox.test.tsx, src/components/filters/checkbox.tsx
Fixes: CAR-8720
So far we checked if facet exists based on the presence of any keys in the facet object and we defaulted to an empty one. This made it impossible to distinguish whether the facet object is not present or empty. In a case where every checkbox in the entire filter would result in zero results, we would treat it as if there were no facets not showing anything and having checkboxes enabled.
The fix on the API level would be tricky and require some post-processing. It would have a negative impact on performance and it's not really feasible.
Instead, we can leverage that an object (even an empty one) is considered truthy so we can roll with a simple `null` check to validate wether we have a facet or it failed to fetch.
=> fix: distingush between null and empty facets

src/components/filters/rangeWithFacets/__tests__/chart.test.tsx, src/components/filters/rangeWithFacets/__tests__/rangeFilterScale.test.ts, src/components/filters/rangeWithFacets/chart.tsx, src/components/filters/rangeWithFacets/sliderWithChart.tsx, src/stories/filters/rangeWithFacets.stories.tsx
Fixes the following issues:
Not sorted facets -> bar is shown even though there are 0 results
When all facets are 0 it looks like this (division by 0 :( )
=> fix: not sorted ranges and all facets 0

src/__tests__/__snapshots__/node.test.ts.snap, src/components/filters/rangeWithFacets/chart.module.css, src/components/filters/rangeWithFacets/chart.tsx, src/tailwind/defaultConfig.ts
CSS modules kick in too late. Since the new filter for price is above the fold, this results in a layout shift. Using global CSS with tailwind hopefully solves this issue.
=> fix: CLS above the fold for the new range filter

src/components/filters/rangeWithFacets/index.tsx, src/components/filters/rangeWithFacets/sliderWithChart.tsx
References: [CAR-9092](https://autoricardo.atlassian.net/browse/CAR-9092)
When the filter is being used on mobile at the moment, the thumb covers the input field while sliding. As a result, the user cannot see the current value. Furthermore, many smartphones have gestures on the side of the screen. Sometimes those are dragged instead of the slider end.
Before
After
=> feat: improve mobile range filter

src/components/modal/index.tsx, src/hooks/__tests__/__snapshots__/useModal.test.tsx.snap
References: [CAR-9077](https://autoricardo.atlassian.net/browse/CAR-9077)
Switches modal close button from `div` to a `button` so that it can be interacted with via voice over.
=> fix: use `button` tag for modal close button

src/__tests__/__snapshots__/node.test.ts.snap, src/tailwind/defaultConfig.ts
Reference: https://github.com/carforyou/carforyou-dealerhub-web/pull/1707
While I was exporting the flash message component I noticed that we were missing the z-index value.
=> fix: added missing tailwind value

src/components/modal/index.tsx, src/hooks/__tests__/__snapshots__/useModal.test.tsx.snap
Reference: https://autoricardo.atlassian.net/browse/CAR-9156
The scrollbar issue is reproduced ONLY on Firefox.
=> fix: fixed horizontal scrollbar

src/components/filters/rangeWithFacets/__tests__/index.test.tsx, src/components/filters/rangeWithFacets/index.tsx, src/components/filters/rangeWithFacets/rangeInputWithUnit.tsx, src/stories/filters/rangeWithFacets.stories.tsx
References: [CAR-9093](https://autoricardo.atlassian.net/browse/CAR-9093)
The slider should be able to show a placeholder to help the user understand possible values. Furthermore, the year field does not have a unit thus it needs to get changed to optional. 
You can see how it looks here: https://github.com/carforyou/carforyou-listings-web/pull/3840
=> feat: allow to pass a placeholder to the range filter

src/__tests__/__snapshots__/node.test.ts.snap, src/components/fieldHelpers/withClearButton.tsx, src/tailwind/defaultConfig.ts
Reference: [CAR-9313](https://autoricardo.atlassian.net/browse/CAR-9313)
We have a bug with the clear icon in the input field because of the **z-index**, now it's removed. I have a [follow-up ticket for UL](https://github.com/carforyou/carforyou-listings-web/pull/3872) for **QA** to check.
[cleanup for DH](https://github.com/carforyou/carforyou-dealerhub-web/pull/1722)
=> fix: removing z-index for clear icon

.circleci/config.yml
References: https://app.circleci.com/pipelines/github/carforyou/carforyou-components-pkg/4360/workflows/a05dd17f-d983-4367-bf7d-6946948a527e/jobs/14194
The deploy scrip was removed, but on CI it still tries to deploy the gh-pages.
=> chore: removed deploy in ci

.storybook/preview.js, package-lock.json, package.json
While I was checking a branch I found that the Storybook Viewport Addon was removed.
Storybook Viewport Addon -> https://storybook.js.org/docs/react/essentials/viewport
I used a lot that addon when I'm working on Storybook. And now that we have the branch deployments on components and header-footer I think, it will be a good practice to use this nice addon that Story provide us.
Maybe you are thinking -> but we can resize the window!. Yes, you can. BUT remember that you are resizing the Storybook itself as well and no ONLY the component.
I added a configuration for the breakpoints.
=> chore: add viewport addon

.storybook/stories/radioButtonGroupWithTitle.stories.tsx, src/components/radioButtonGroupWithTitle.tsx, src/index.ts
References [CAR-9534](https://autoricardo.atlassian.net/browse/CAR-9534)
Related PR : https://github.com/carforyou/carforyou-listings-web/pull/4030
Currently we dont have a component that returns a group of `RadioButton` with a global title. It could be useful in some cases, for example, to solve the issue of the related PR linked above.
In case this PR is approved, I'll create a task to replace the current occurences
=> Car 9534: new component "radioButtonGroupWithTitle"

package.json
It was not possible to open type definitions or autocomplete the props in your IDE because the path was missing in package.json
=> fix: path to types in package.json
