carforyou/carforyou-components-pkg

src/components/select.tsx
fixes: https://autoricardo.atlassian.net/browse/CAR-4400
=> fix: disable the clear button when select is disabled

src/components/__tests__/__snapshots__/button.test.tsx.snap, src/components/segmentedControl/__tests__/__snapshots__/index.test.tsx.snap, src/lib/buttonHelper.tsx
[CAR-4552 - IE - button labels are not centered](https://autoricardo.atlassian.net/browse/CAR-4552)
Branch deployment for testing -> https://github.com/carforyou/carforyou-listings-web/pull/2204
=> fix: center button text on ie

src/components/modal/index.tsx, src/hooks/useModal.tsx
Adds the ability to pass a onClose callback to a modal
=> feat: onClose function for modals

package.json
see carforyou/carforyou-dealerhub-web#563 for details
=> chore: pin internal dependencies

.storybook/webpack.config.js, README.md, assets/index.css, package-lock.json, package.json, src/components/intercom/index.module.css, src/components/intercom/index.tsx, tsconfig.json, tsconfig.pika.json, typings.d.ts
https://autoricardo.atlassian.net/browse/CAR-4713
this is a demo implementation of how to use css modules in the pkg.
=> fix: use css modules for intercom

package-lock.json, package.json
uses rollup 2 for building (again)
=> fix: update build dependencies

package-lock.json, package.json, src/components/radioButton.tsx, src/components/tooltip/index.tsx
We closed renovate PR so a manual update is needed.
=> chore: update eslint config

src/__tests__/__snapshots__/node.test.ts.snap, src/tailwind/defaultConfig.ts
After discussing this in the RFC https://github.com/carforyou/carforyou-docs/issues/72 here is the implementation
=> feat: add new breakpoint xxs

package-lock.json, src/components/__tests__/collapsible.test.tsx, src/components/collapsible.tsx
We have a case where we need to be able to control the state of a collapsible from the outside.
An alternative to this approach would be to have a collapsible list component delivered by this package. It would then use a different item than the collapsible that is exported outside.
=> BREAKING CHANGE: force collapse of a collapsible

src/components/datePicker/index.tsx
allow datePicker to receive disabled property
=> feat: allow datePicker to be disabled

src/components/filters/__tests__/checkbox.test.tsx, src/components/filters/checkbox.tsx, src/stories/filters/checkbox.stories.tsx
While working on the checkboxFilter component extraction, we were skipping to pass the tracking. 
Now, the tracking is added as an optional prop.
PR in listings -> https://github.com/carforyou/carforyou-listings-web/pull/3066
=> CAR-6339: feat: extended checkboxFilter component with tracking

src/components/icons/ribbon.tsx, src/components/icons/verified.tsx, src/components/verifiedRibbon.tsx, src/index.ts, src/stories/verifiedRibbon.stories.tsx
Add the verified ribbon as it's used both in listings and DH.
=> feat: add verified ribbon component

src/components/intercom/index.tsx
> Jira https://autoricardo.atlassian.net/browse/CAR-7862
I have checked with Enrique about the options to fix this case and here is the solution:
Solution: add a border -> color grey-4 -> width 1px. 
https://www.figma.com/file/whRHY1alG2bVuGpX9m5rQY/BUG-Fixing?node-id=2%3A822114
=> fix: make more visible the intercom button

src/components/icons/closeM.tsx, src/components/modal/index.tsx, src/hooks/__tests__/__snapshots__/useModal.test.tsx.snap, src/hooks/useModal.tsx, src/stories/modal.stories.tsx
> Jira https://autoricardo.atlassian.net/browse/CAR-8086
The issue could be fixed individually and faster in listings but we can face the same issue in the future. Therefore, the fix lies in the modal component.
Please check the adjustments in DH and listings before you approve this PR:
**DH:** https://github.com/carforyou/carforyou-dealerhub-web/pull/1426
**Listings:** https://github.com/carforyou/carforyou-listings-web/pull/3388
=> fix: adjust title and close on modal

src/components/checkbox.tsx, src/components/fieldHelpers/withHorizontalLabel.tsx, src/components/filters/__tests__/__snapshots__/checkbox.test.tsx.snap
Hackdays - Video Request
I added the following prop `alignItems="start" | "center` in order to have more control over the vertical alignment of the label for checkboxes and radio buttons. 
It allows me to improve the [video request checkbox](https://github.com/carforyou/carforyou-listings-web/pull/3533) in the Whatsapp Modal.
Thank you 📹
=> feat: update checkbox component

src/components/__tests__/image.test.tsx, src/components/image.tsx
https://autoricardo.atlassian.net/browse/CAR-8495
=> feat: allow images to lazy load

src/components/intercom/index.module.css, src/components/intercom/index.tsx
https://autoricardo.atlassian.net/browse/CAR-8372
=> fix: show only intercom icon on mobile version

src/components/asterisk.tsx, src/components/fieldHelpers/label.tsx, src/components/fieldHelpers/withFloatingLabel.tsx, src/components/fieldHelpers/withLabel.tsx, src/components/input/index.tsx, src/stories/input/floatingLabel.stories.tsx
[CAR-8373](https://autoricardo.atlassian.net/browse/CAR-8373)
adding asterisk for the required field (floatingLabel)
~~add requreid for requreid fields in DH~~
=> feat: added asterisk for required field

src/components/alertMessage.tsx, src/components/flashMessage/__tests__/index.test.tsx, src/components/flashMessage/__tests__/message.test.tsx, src/components/flashMessage/context/__tests__/provider.test.tsx, src/components/flashMessage/context/context.ts, src/components/flashMessage/context/index.ts, src/components/flashMessage/context/provider.tsx, src/components/flashMessage/index.tsx, src/components/flashMessage/message.tsx, src/index.ts, src/stories/flashMessage.stories.tsx
https://autoricardo.atlassian.net/browse/CAR-8998
Exports the flash message concept from dealerhub and unifies the style with our alert messages.
In order to provide flash messages in the application, the provider and container must be added to the app
```
<FlashMessagesProvider>
<FlashMessages />
<p>Content</p>
</FlashMessagesProvider>
````
To use add a flash message from any component the provided context can be used
you must specify a type and the content. optionally a delay in ms can be defined to automatically close the message. further on an optional onClose handler can be passed to the message if neeed.
```
const { addMessage } = useContext(FlashMessagesContext)
const add = () => addMessage({ type, content: dummyText, autoCloseDelay })
```
=> CAR-8998 flash messages

.dockerignore, Dockerfile, package-lock.json, package.json
Reference: https://autoricardo.atlassian.net/browse/CAR-7013
The first step for the branch deployment.
* Creation of the `Dockerfile`
1. Build the image -> `docker build -t <image_name>`
2. Run the container -> `docker run -it -p 8008:8008 <image_name>`
=> chore: added Dockerfile

.circleci/config.yml, README.md, helm-chart/Chart.yaml, helm-chart/branch.values.yaml, helm-chart/templates/deployment.yaml, helm-chart/templates/ingress.yaml, helm-chart/templates/namespace.yaml, helm-chart/templates/secret.yaml, helm-chart/templates/service.yaml, helm-chart/values.yaml
References: https://autoricardo.atlassian.net/browse/CAR-9434
The second step for the branch deployment: circleci + upload.
The third step for the branch deployment: added the helm chart -> circleci deploys to k8s
I already added the webhook on gitHub.
=> chore: circleci build

helm-chart/values.yaml
Datadog dashboard:
https://app.datadoghq.com/notebook/1750667/virginia-jan-04-2022-13-56?start=1640705304684&range=604800000&live=true
The branch deployments are on the `teal` cluster.
=> chore: adjusted resources value

src/components/filters/input.tsx
References [CAR-9423](https://autoricardo.atlassian.net/browse/CAR-9423?atlOrigin=eyJpIjoiOTYxYjE1MDVkYTY1NGYxZWI1ODNkNTFlYjcyZjg4MWQiLCJwIjoiaiJ9)
Related PR : [DH](https://github.com/carforyou/carforyou-dealerhub-web/pull/1782), [Listings](https://github.com/carforyou/carforyou-listings-web/pull/3961)
Type field is automatically filled with “undefined”
Type field is left empty
=> fix: inputFilter

src/tailwind/defaultConfig.ts
I will apply the divideWidth/Color in our projects and make a clean up around the styles. I just add some comments for it.
DH is in progress...
=> chore: added link for divideWidth
